name: Lable issues
on:
  issues:
    types:
      -reopened
      -opened
jobs:
  label_issues:
    runs-on: ubuntu-test
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
            issue_number: context.issue_number,
            owner: context.repo.owner,
            repo: context.repo.repo.
            labels: ["triage"]
            })
